// Licensed under the Mozilla Public License 2.0
// SPDX-License-Identifier: MPL-2.0

import Foundation

/// Precomputed pseudo-random keys used for incremental Zobrist hashing of
/// chess positions. All keys are 64-bit so they remain stable across the
/// Swift ↔ Kotlin boundary (Skip maps ``Int64`` to Kotlin's ``Long``).
///
/// Hashes are generated by a deterministic xorshift64 generator so the same
/// keys are produced on every platform without storing megabytes of tables.
public enum Zobrist {

    // 15 piece codes × 64 squares; some entries (for codes 0, 7, 8) are
    // unused but the wider table simplifies indexing by the compact piece
    // encoding without an extra mapping step.
    public static let pieceKeys: [Int64] = makePieceKeys()
    public static let sideToMoveKey: Int64 = makeSideKey()
    public static let castlingKeys: [Int64] = makeCastlingKeys()
    public static let enPassantFileKeys: [Int64] = makeEnPassantFileKeys()

    @inlinable
    public static func keyForPiece(_ code: Int, square: Int) -> Int64 {
        return pieceKeys[code * 64 + square]
    }

    @inlinable
    public static func keyForCastlingRights(_ rights: Int) -> Int64 {
        return castlingKeys[rights & 0xF]
    }

    @inlinable
    public static func keyForEnPassantSquare(_ square: Int) -> Int64 {
        if square < 0 {
            return 0
        }
        return enPassantFileKeys[square & 7]
    }

    // MARK: - Xorshift64 generator (deterministic across platforms)

    private static func xorshift(_ state: Int64) -> Int64 {
        var s = state
        s = s ^ (s << 13)
        s = s ^ (s >> 7)
        s = s ^ (s << 17)
        return s
    }

    private static func makePieceKeys() -> [Int64] {
        var state: Int64 = 81985529216486895  // 0x123456789ABCDEF
        var keys = [Int64](repeating: 0, count: 15 * 64)
        for i in 0..<keys.count {
            state = xorshift(state)
            keys[i] = state
        }
        return keys
    }

    private static func makeSideKey() -> Int64 {
        // Advance the generator past piece keys so this key doesn't collide.
        var state: Int64 = 81985529216486895
        for _ in 0..<(15 * 64) {
            state = xorshift(state)
        }
        state = xorshift(state)
        return state
    }

    private static func makeCastlingKeys() -> [Int64] {
        var state: Int64 = 81985529216486895
        for _ in 0..<(15 * 64 + 1) {
            state = xorshift(state)
        }
        var keys = [Int64](repeating: 0, count: 16)
        for i in 0..<keys.count {
            state = xorshift(state)
            keys[i] = state
        }
        return keys
    }

    private static func makeEnPassantFileKeys() -> [Int64] {
        var state: Int64 = 81985529216486895
        for _ in 0..<(15 * 64 + 1 + 16) {
            state = xorshift(state)
        }
        var keys = [Int64](repeating: 0, count: 8)
        for i in 0..<keys.count {
            state = xorshift(state)
            keys[i] = state
        }
        return keys
    }
}
